version: '3'

services:
  backend:
    build: backend
    env_file: .env
    volumes:
      - ./backend/code:/code
    command: ./scripts/start_dev
    ports:
      - "${BACKEND_PORT:-8000}:8000"

  postgres:
    image: postgres:10.1
    env_file: .env
    labels:
      - "traefik.enable=false"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
