version: '3.3'

services:
  nginx:
    image: nginx:1.13.8
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx

  backend:
    build:
      context: backend
      args:
        IS_DEV: "true"
    env_file: .env
    volumes:
      - ./backend/code:/code
    command: ./scripts/start_dev
    labels:
      - "traefik.backend=backend"
      - "traefik.frontend.rule=PathPrefixStrip:/api/"

  frontend:
    build:
      context: frontend
      args:
        IS_DEV: "true"
    env_file: .env
    volumes:
      - ./frontend/code:/code
    command: npm run dev
    labels:
      - "traefik.backend=frontend"
      - "traefik.frontend.rule=PathPrefix:/"

  postgres:
    image: postgres:10.1
    env_file: .env
    labels:
      - "traefik.enable=false"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
